### ISSUE TITLE
Retain cycles's cell is red,but when I tap, it still to find retain cycles again.

### ISSUE THREAD

**Issue by c-xiaoqiang** [facebook/FBMemoryProfiler#14]
I just want to find it once.But it has to find retain cycle every time.Can you support it?

- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath
{
  // Retain cycle detection kicks in
  NSString *className = [tableView cellForRowAtIndexPath:indexPath].textLabel.text;
  NSInteger generationIndex = indexPath.section;

  [self _findRetainCyclesForClassesNamed:@[className]
                            inGeneration:generationIndex
                          presentDetails:YES];
}

**Comment by Gricha** [comment]
Hey, the results are not cached anywhere at the moment, if you tap on red cell and it shows up green again, it probably means the retain cycle disappeared by now (because we run retain cycle for the second time).

I'm a little skeptical about how to support it, because all cycles are currently hold weakly so even if we hold them, we would present just nils - not very helpful. We could cache the description of that cycle, but maybe if it already disappeared, it's not so bad.

If you have a suggestion of how it could be implemented, we are happy to take a pull request!
